### ISSUE TITLE
ip ban problem

### ISSUE THREAD

**Issue by tailon222** [HerrEurobeat/steam-idler#1]
Hi! the script works amazingly well when logging into accounts but i have problem and it is that when i lose the conexion becouse my internet just turn off, when my internet goes back on it tries to relog in all accounts at the same time. is there anyway to make the same cooldown as it is with the account normal logging. I'm sorry if i explained this a bit bad, my english sucks and i'm not a programmer. Thank you!.

**Comment by HerrEurobeat** [comment]
Alright, I worked on the project today and released version 1.2.  
It contains a relog queue to fix this problem as well as a few more goodies.  
  
I hope this solves your issue. If there is something else please let me know! :)

**Comment by tailon222** [comment]
Hell yeah! thank you so much, it will help a lot since i'm trying to boost 50 accounts. I'll test it if i have any other problem will let you know, again, thank you so much :) .
