### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by otherwise33** [HerrEurobeat/steam-idler#2]
Hi, getting this error in my VDS. Why this is happening? Can you help me please if ur available?
![image](https://user-images.githubusercontent.com/111538512/185495827-fe0e8a74-99a7-4922-8948-148033340272.png)

**Comment by otherwise33** [comment]
![image](https://user-images.githubusercontent.com/111538512/185510634-6617a1a3-3a63-4f14-a261-2c36fcff0a18.png)
And this is another error.

**Comment by otherwise33** [comment]
![image](https://user-images.githubusercontent.com/111538512/185510729-a2626193-7081-4c76-bc98-ad0c8c265550.png)
Full of no connection one.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Does this happen always on start? If so, is your firewall or something else maybe blocking the application from accessing Steam?  
Otherwise I might have made a mistake handling the error event when a login fails

**Comment by otherwise33** [comment]
Hi thanks for reply. It doesnt happening in the start, happening in random times while boosting, and it closes itself. 
`echo off
title idler
cls
:a
node idler.js
goto a
pause ``

I write this codes into text file, and saved as in .bat file. And it is restarting the script when it is down. I able to see error codes with this bat file. Everything is okay since 22.00 PM. I dont know why this is happening.

**Comment by HerrEurobeat** [comment]
Ah if it's happening at random times then it looks like a normal disconnect. It happens all the time that an account looses connection for a short moment to Steam.  
No idea however why the script crashes for you, it should attempt to relog all accounts that are used and lost connection one after another.  
I'll look into it and see if I can find something, thanks for reporting

**Comment by tailon222** [comment]
Hi @HerrEurobeat! i was testing the app on my own pc, and i did a "fake disconnect" (plug out and plug in the ethernet cable). I get the same error that is described by @otherwise33 . i don't think it's normal that the app cashes when there is no internet. Somehow i edited one script that i found in github (I don't know how to code), and it doesn't crash when there's not internet.
This is the code: https://pastebin.com/F42PB9aT  (i don't know if it has something to do with the script itself).
What i was thinking is that in line 96 you are trying handle relogging when "disconnected"  what i think that it does is that if the account disconnects becouse of steam servers problems it will relog but you have to have internet in the device that is hosted the script. Now, if you don't have internet it throws an error and i don't see any error handlers like in the script that i have linked (line 18). As i said i don't know how to code, just trying to understand the script. Thank you! 
![screenshto](https://user-images.githubusercontent.com/65341637/196033976-d3a4a8a9-210d-4be6-b4db-d212e8936c28.JPG)

**Comment by HerrEurobeat** [comment]
Hey, yeah it looks like an error event is thrown instead of disconnected, leading to the application crashing, which should ofc not happen.  
Since I'm planning to update the script soon anyway to add support for the new login flow I'm going to fix this as well.  
Shouldn't be too much work anyway as I have the relog system working perfectly in my steam-comment-service-bot.

Thanks for reporting and investigating!

**Comment by tailon222** [comment]
Thank you for the fast response, i will be looking at the repository :)

**Comment by tailon222** [comment]
Okay, thank you for taking the time! i will let you know if something happens :)

**Comment by tailon222** [comment]
Thank you for taking the time! i'm testing the script and in the console everything seems good : 
![fhfgh](https://user-images.githubusercontent.com/65341637/196581612-2c04036e-9748-417c-af93-623e540142ed.JPG)
But when i look at steam the account is not actually playing nor online (yes, i have set the status at 1 which is Online). 
I did a "fake disconnect" like i did in the other version  and when it relogs starts playing games and the account is online.

**Comment by HerrEurobeat** [comment]
Hm thats weird. That was one of the things I tested and it worked for me, also the login and relog trigger the same piece of code which starts playing games so this behavior should technically be impossible...  
I'll look into it later.

**Comment by tailon222** [comment]
The thing is that is not that the account won't set online and start idling as i'm looking at the page https://steamcommunity.com/id/YOURSTEAMID/games/?tab=all  and it doesn't show the login session which for me that
means that is not even logged in.
What i'm talking about: 
![Captura](https://user-images.githubusercontent.com/65341637/196675172-f1ba71a4-278e-40a7-9818-827e24409547.JPG)

it just doesn't show at all.

**Comment by HerrEurobeat** [comment]
Hm, for me it looks like this. First time I started it today so the last played date is fresh:
![image](https://user-images.githubusercontent.com/35304405/196676511-a4c29b09-db11-43a9-8554-fca0d85985d5.png)

**Comment by tailon222** [comment]
It has to be something on my end, the thing is that the console says that is idling but is not, maybe i installed bad the required 
packages? becouse it threw me some errors that was " cannot find mode 'steam-sessions' and other 2 more but i installed them. So i don't know what it could be.

**Comment by HerrEurobeat** [comment]
I left it running for 30 minutes now and can confirm that the playtime increased, so it seems to be working.  
Yes, you need to run `npm install` after you updated as I added two packages and updated one. If a package is missing then the "Cannot find module 'x'" error you mentioned occurrs.

**Comment by tailon222** [comment]
This is what i get then i run npm install
![no no no](https://user-images.githubusercontent.com/65341637/196684717-61df1772-3f9f-4180-b0cb-34c68a77a5df.JPG)

I think that if the required packages aren't installed correctly then the app won't even start
So i don't know has to be something on my pc.

**Comment by otherwise33** [comment]
Is there any problem for using old version? Because if i want to use new one i must enter guard codes, its not easy for me.

**Comment by HerrEurobeat** [comment]
You need to input the steam guard code once again for all accounts as Valve changed Steam's login flow.  
A token will then be stored in a database and will be reused for following logins.  
  
Sure, you can use the older version if you don't need the fixes of the newer version however it may stop working at any time when Steam stops supporting the old login flow.
