### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by foytak** [HerrEurobeat/steam-idler#3]
![image](https://user-images.githubusercontent.com/62214637/187060303-d097a239-f3d9-44cb-bfcc-8c568496c224.png)
i m getting this error.

**Comment by foytak** [comment]
This error solved.
And this error happening , "Error: Cannot find module 'output-logger'"

**Comment by HerrEurobeat** [comment]
Looks like you found the solution already, however for anyone else who might find this:  
You forgot to run `npm install` to install all dependencies
