### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by T4lk** [HerrEurobeat/steam-idler#7]
![image](https://user-images.githubusercontent.com/76187598/228652538-5ea5f760-e46f-4e61-ad4b-d1d4c09dd530.png)
It just tells me goodbye

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
I had this issue once too but wasn't able to replicate it consistently. I think it has something to do with it failing to load the logininfo from `accountx.txt` as some editors automatically format the file differently.  
I can check if I'm able to replicate the issue again and will let you know!

**Comment by HerrEurobeat** [comment]
So I've been able to replicate the issue. It seems like this happens when the `accounts.txt` file has an empty last line - which is something some text editors always append.  
I'm not sure why this confuses the bot but we'll see.

**Comment by HerrEurobeat** [comment]
Should be fixed now. I'll comment again when version 1.5 is out.  
Please let me know should you run into the issue again. Thanks!

**Comment by T4lk** [comment]
thanks for a pretty fast response

**Comment by HerrEurobeat** [comment]
Version 1.5 is now out which includes the fix for this issue.
